# Generated by Django 5.0.2 on 2024-02-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="books",
            field=models.CharField(default="test", max_length=10),
        ),
    ]
