# Generated by Django 5.0.2 on 2024-02-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_project_books"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cultures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("cultureName", models.CharField(max_length=100)),
                ("collector", models.CharField(max_length=100)),
                ("photos", models.CharField(max_length=100)),
            ],
        ),
    ]
